/jetson_csi_camera_ros2_driver_node:
  ros__parameters:
    ##### 카메라 관련 매개변수 #####
    camera_id: 0          # 카메라 번호
    image_width: 400      # 이미지 가로 픽셀 크기
    image_height: 300     # 이미지 세로 픽셀 크기
    frame_id: camera_link # SLAM